# Generated by Django 5.2.8 on 2025-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=10),
        ),
    ]
