# Generated by Django 5.2.8 on 2025-11-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0002_remove_parkingslot_is_occupied_parkingslot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitoring_slots', models.ManyToManyField(related_name='cameras', to='parking.parkingslot')),
            ],
        ),
        migrations.CreateModel(
            name='OCRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_logs', to='camera_ocr.camera')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_logs', to='parking.parkingslot')),
            ],
        ),
    ]
